from . import CppBindingGenerator as cbg
import ctypes
import sys

# from .common import *

EasingType = cbg.Enum('Altseed', 'EasingType')
with EasingType as enum:
    enum.brief = cbg.Description()
    enum.brief.add('ja', 'イージングの種類を表す')
    enum.add('Linear')
    enum.add('InSine')
    enum.add('OutSine')
    enum.add('InOutSine')
    enum.add('InQuad')
    enum.add('OutQuad')
    enum.add('InOutQuad')
    enum.add('InCubic')
    enum.add('OutCubic')
    enum.add('InOutCubic')
    enum.add('InQuart')
    enum.add('OutQuart')
    enum.add('InOutQuart')
    enum.add('InQuint')
    enum.add('OutQuint')
    enum.add('InOutQuint')
    enum.add('InExpo')
    enum.add('OutExpo')
    enum.add('InOutExpo')
    enum.add('InCirc')
    enum.add('OutCirc')
    enum.add('InOutCirc')
    enum.add('InBack')
    enum.add('OutBack')
    enum.add('InOutBack')
    enum.add('InElastic')
    enum.add('OutElastic')
    enum.add('InOutElastic')
    enum.add('InBounce')
    enum.add('OutBounce')
    enum.add('InOutBounce')

Vector2I = cbg.Struct('Altseed', 'Vector2I')
Vector2F = cbg.Struct('Altseed', 'Vector2F_C')
Vector3F = cbg.Struct('Altseed', 'Vector3F')
RectF = cbg.Struct('Altseed', 'RectF')
Matrix44F = cbg.Struct('Altseed', 'Matrix44F')
